blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://github.com/protonemedia/laravel-splade-docs
    about: For documentation issues, open a pull request at the protonemedia/laravel-splade-docs repository